### ISSUE TITLE
Availability on Mac OS?

### ISSUE THREAD

**Issue by LifeWorks** [mms-fcul/PypKa#20]
Hi 

Thanks for providing this useful tool. I came across to use it on MAC machine and find out that it can not run on mac. The reason is that all the cython compiled .so files are for linux system. I wonder would you mind provide some guidance or the makefiles to compile corresponding .so files for mac system as well?

Thanks very much!

**Comment by pedrishi** [comment]
hey! unfortunately we can not use PypKa on Mac. The problem is not the cython compilation, but since we can't fix the other issue we didn't ship the cython .so files for mac.

could you make do with using the CLI? if so, you could use PypKa via docker as described in the [documentation](https://pypka.readthedocs.io/en/latest/getting_started/installation.html#via-docker):

> docker run -v ${PWD}:/home/ -w /home -t pedrishi/pypka:latest python3.9 -m pypka <PARAMETERS_FILE>
